name: "Agda RTLIL CI"
on:
  push:
    branches:
      - main

jobs:
  dev-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: famisoft
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop --profile dev-shell -c true

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: cachix/cachix-action@v15
      with:
        name: famisoft
        skipPush: true
    - run: nix flake check

  typecheck:
    runs-on: ubuntu-latest
    needs: dev-shell
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: famisoft
        skipPush: true
    - run: nix build -L
